# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: econ_gcmessages.proto
# plugin: python-betterproto

from dataclasses import dataclass
from typing import List

import betterproto

from ....protobufs.msg import GCProtobufMessage
from ..enums import Language


@dataclass(eq=False, repr=False)
class GiftedItems(betterproto.Message):
    accountid: int = betterproto.uint32_field(1)
    giftdefindex: int = betterproto.uint32_field(2)
    max_gifts_possible: int = betterproto.uint32_field(3)
    num_eligible_recipients: int = betterproto.uint32_field(4)
    recipients_accountids: List[int] = betterproto.uint32_field(5)


@dataclass(eq=False, repr=False)
class ApplyAutograph(betterproto.Message):
    autograph_item_id: int = betterproto.uint64_field(1)
    item_item_id: int = betterproto.uint64_field(2)


class CasketItemAdd(GCProtobufMessage, msg=Language.CasketItemAdd):
    casket_item_id: int = betterproto.uint64_field(1)
    item_item_id: int = betterproto.uint64_field(2)


class CasketItemExtract(GCProtobufMessage, msg=Language.CasketItemExtract):
    casket_item_id: int = betterproto.uint64_field(1)
    item_item_id: int = betterproto.uint64_field(2)


class CasketItemLoadContents(GCProtobufMessage, msg=Language.CasketItemLoadContents):
    casket_item_id: int = betterproto.uint64_field(1)
    item_item_id: int = betterproto.uint64_field(2)


@dataclass(eq=False, repr=False)
class UserTrackTimePlayedConsecutively(betterproto.Message):
    state: int = betterproto.uint32_field(1)


class ItemCustomizationNotification(GCProtobufMessage, msg=Language.ItemCustomizationNotification):
    item_id: List[int] = betterproto.uint64_field(1)
    request: int = betterproto.uint32_field(2)
