# Configuration file for the Sphinx documentation builder.
#
# This file only contains a selection of the most common options. For a full
# list see the documentation:
# https://www.sphinx-doc.org/en/master/usage/configuration.html

from __future__ import annotations

import builtins
import os
import sys
from pathlib import Path

builtins.__sphinx__ = True  # type: ignore

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.

sys.path.insert(0, os.path.abspath(".."))
sys.path.append(os.path.abspath("extensions"))
from docs.extensions import ROOT

# -- General configuration ------------------------------------------------

# General information about the project.
project = "steam-ext-csgo"
copyright = "2020, Gobot1234"

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = [
    "sphinx.ext.autodoc",
    "sphinx.ext.extlinks",
    "sphinx.ext.intersphinx",
    "sphinx.ext.napoleon",
    "sphinxcontrib_trio",
    "myst_parser",
    *(p.stem for p in Path("extensions").glob("*.py") if not p.stem.startswith("_")),
]

autodoc_member_order = "bysource"

# Links used for cross-referencing stuff in other documentation
intersphinx_mapping = {
    "py": ("https://docs.python.org/3", None),
    "aio": ("https://docs.aiohttp.org/en/stable", None),
    "steam": ("https://steam-py.github.io/docs/latest", None),
}

rst_prolog = """
.. |coro| replace:: This function is a |coroutine_link|_.
.. |maybecoro| replace:: This function *could be a* |coroutine_link|_.
.. |coroutine_link| replace:: *coroutine*
.. _coroutine_link: https://docs.python.org/3/library/asyncio-task.html#coroutine
.. |maybecallabledeco| replace:: A decorator that *could be called*.
"""

# The suffix of source filenames.
source_suffix = ".rst"

# The master toctree document.
master_doc = "index"

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = None

locale_dirs = ["locale/"]
gettext_compact = False

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
exclude_patterns = ["_build"]

# The name of the Pygments (syntax highlighting) style to use.
pygments_style = "friendly"


# -- Options for HTML output ----------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
html_theme = "furo"

html_context = {
    "discord_invite": "https://discord.gg/MQ68WUS",
    "repository": "https://github.com/Gobot1234/steam-ext-csgo",
}

extlinks = {
    "issue": (f"{html_context['repository']}/%s", "GH-"),
}

resource_links = {
    "discord": html_context["discord_invite"],
    "issues": f"{html_context['repository']}/issues",
    "examples": f"{html_context['repository']}/tree/main/examples",
}

# The name of an image file (within the static path) to use as favicon of the
# docs.  This file should be a Windows icon file (.ico) being 16x16 or 32x32
# pixels large.
html_favicon = "images/favicon.ico"
